name: async-single-threaded

on:
  pull_request:
  push:
    branches: [main]

jobs:
  asyncio_single_threaded:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    - name: Run asyncio_single_threaded
      run: |
        python -m asyncio_single_threaded
